---
- hosts: 172.31.89.158
  
  tasks:
     - name: Creating a user with customized path
       user:
         name: customuser
         password: $1$iOHbObrJ$omAXIzzP2bXhLDYgVr5x21
         state: present
         shell: /bin/bash
         system: no
         createhome: yes
         home: /custom/customuser
