pipeline {
      agent any
      stages {
         stage('clone repo'){
         stage('dev playbook') {
            steps {
            sh "ansible-playbook newdir/multi.yml -b"
        }
      }
    }
  }
}
