pipeline {
      agent {
         node {
           label 'master'
         }
      }
      
      stages {
         stage('dev playbook') {
            steps {
            sh "ansible-playbook nginx.yml -b"
       }
    }
  }
}
